// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MkWMS.Data.Context;

#nullable disable

namespace MkWMS.Data.Migrations
{
    [DbContext(typeof(MkWMSDbContext))]
    partial class MkWMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MkWMS.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Действие");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ДатаДействия");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("ПользовательId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ЖурналДействий", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("НомерПартии");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("СрокГодности");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ТоварId");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ДатаПроизводства");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Партии", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Название");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("СкладId");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Подразделения", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Комментарий");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("СозданПользователемId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ДатаСоздания");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("ПодразделениеId");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("НомерДокумента");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ТипДокументаId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Статус");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("СкладId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DocumentNumber")
                        .HasDatabaseName("IX_Документы_Номер");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Документы", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.DocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("ПартияId");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("ДокументId");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Цена");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ТоварId");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Количество");

                    b.Property<int?>("SerialNumberId")
                        .HasColumnType("int")
                        .HasColumnName("СерийныйНомерId");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_СтрокиДокументов_Документ");

                    b.HasIndex("ProductId");

                    b.HasIndex("SerialNumberId");

                    b.ToTable("СтрокиДокументов", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Название");

                    b.HasKey("Id");

                    b.ToTable("ТипыДокументов", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Артикул");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Штрихкод");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ДатаСоздания");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Название");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ЕдиницаИзмерения");

                    b.Property<bool>("UseBatches")
                        .HasColumnType("bit")
                        .HasColumnName("ИспользоватьПартии");

                    b.Property<bool>("UseSerialNumbers")
                        .HasColumnType("bit")
                        .HasColumnName("ИспользоватьСерийныеНомера");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("IX_Товары_Штрихкод");

                    b.ToTable("Товары", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Название");

                    b.HasKey("Id");

                    b.ToTable("Роли", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("СерийныйНомер");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ТоварId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Статус");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("СерийныеНомера", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.StockBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("ПартияId");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ТоварId");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Количество");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("СкладId");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ProductId", "WarehouseId")
                        .HasDatabaseName("IX_Остатки_ТоварСклад");

                    b.ToTable("Остатки", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("ПартияId");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("ДокументId");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ДатаДвижения");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ТоварId");

                    b.Property<decimal>("QuantityChange")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("ИзменениеКоличество");

                    b.Property<int?>("SerialNumberId")
                        .HasColumnType("int")
                        .HasColumnName("СерийныйНомерId");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("СкладId");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Движения_Товар");

                    b.HasIndex("SerialNumberId");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_Движения_Склад");

                    b.ToTable("ДвиженияТоваров", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ДатаСоздания");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ФИО");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Активен");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Логин");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ХешПароля");

                    b.Property<bool>("RequiresPasswordChange")
                        .HasColumnType("bit")
                        .HasColumnName("ТребуетсяСменаПароля");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("UX_Пользователь_Логин");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Пользователи", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("РольId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("ПользовательId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_Пользователь_Роль");

                    b.ToTable("ПользователиРоли", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Адрес");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Активен");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Название");

                    b.HasKey("Id");

                    b.ToTable("Склады", (string)null);
                });

            modelBuilder.Entity("MkWMS.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("MkWMS.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Batch", b =>
                {
                    b.HasOne("MkWMS.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Department", b =>
                {
                    b.HasOne("MkWMS.Data.Entities.Warehouse", "Warehouse")
                        .WithMany("Departments")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Document", b =>
                {
                    b.HasOne("MkWMS.Data.Entities.User", "CreatedByUser")
                        .WithMany("CreatedDocuments")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MkWMS.Data.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("MkWMS.Data.Entities.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MkWMS.Data.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Department");

                    b.Navigation("DocumentType");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.DocumentItem", b =>
                {
                    b.HasOne("MkWMS.Data.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId");

                    b.HasOne("MkWMS.Data.Entities.Document", "Document")
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MkWMS.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MkWMS.Data.Entities.SerialNumber", "SerialNumber")
                        .WithMany()
                        .HasForeignKey("SerialNumberId");

                    b.Navigation("Batch");

                    b.Navigation("Document");

                    b.Navigation("Product");

                    b.Navigation("SerialNumber");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.SerialNumber", b =>
                {
                    b.HasOne("MkWMS.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.StockBalance", b =>
                {
                    b.HasOne("MkWMS.Data.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId");

                    b.HasOne("MkWMS.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MkWMS.Data.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.StockMovement", b =>
                {
                    b.HasOne("MkWMS.Data.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId");

                    b.HasOne("MkWMS.Data.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MkWMS.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MkWMS.Data.Entities.SerialNumber", "SerialNumber")
                        .WithMany()
                        .HasForeignKey("SerialNumberId");

                    b.HasOne("MkWMS.Data.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Document");

                    b.Navigation("Product");

                    b.Navigation("SerialNumber");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.User", b =>
                {
                    b.HasOne("MkWMS.Data.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.UserRole", b =>
                {
                    b.HasOne("MkWMS.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MkWMS.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Document", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.User", b =>
                {
                    b.Navigation("CreatedDocuments");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MkWMS.Data.Entities.Warehouse", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
